#!/usr/bin/env python3
"""Generate meta-package PKGBUILDs from manifest.yaml.

Run as a build step in .github/workflows/build.yml, right before packages
are built. Output is never committed -- each `modules.<name>` (and each
`modules.live_install.subgroups.<name>`) becomes a `bitglyph-<name>-meta`
directory with a generated PKGBUILD whose `depends=()` mirrors the
manifest's package list. Regenerated from scratch on every build.
"""
import sys
from datetime import datetime, timezone
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
MANIFEST_PATH = REPO_ROOT / "manifest.yaml"
MARKER = "# GENERATED FILE"
PKGVER = datetime.now(timezone.utc).strftime("%Y%m%d")

PKGBUILD_TEMPLATE = """{marker} -- do not edit directly, do not commit.
# Generated by ci/generate_meta_packages.py from manifest.yaml.
pkgname={pkgname}
pkgver={pkgver}
pkgrel=1
pkgdesc="{pkgdesc}"
arch=('any')
url="https://github.com/BitGlyph/bitglyph-PKGBUILDs"
license=('MIT')
depends=(
{depends}
)

package() {{
  : # nothing to install, this exists purely to pull in dependencies
}}
"""


def slugify(name: str) -> str:
    return name.replace("_", "-")


def clean_description(desc: str) -> str:
    return " ".join(desc.split()).replace('"', "'")


def collect_groups(manifest: dict) -> dict[str, dict]:
    """Flatten modules (and live_install subgroups) into pkgname -> {description, packages}."""
    groups = {}
    for mod_name, mod in manifest["modules"].items():
        if "subgroups" in mod:
            for sub_name, sub in mod["subgroups"].items():
                pkgname = f"bitglyph-{slugify(mod_name)}-{slugify(sub_name)}-meta"
                groups[pkgname] = {
                    "description": sub.get("description", ""),
                    "packages": sub.get("packages", []),
                }
        else:
            pkgname = f"bitglyph-{slugify(mod_name)}-meta"
            groups[pkgname] = {
                "description": mod.get("description", ""),
                "packages": mod.get("packages", []),
            }
    return groups


def render_pkgbuild(pkgname: str, description: str, packages: list[str]) -> str:
    depends_block = "\n".join(f"  {pkg}" for pkg in packages)
    return PKGBUILD_TEMPLATE.format(
        marker=MARKER,
        pkgname=pkgname,
        pkgver=PKGVER,
        pkgdesc=clean_description(description),
        depends=depends_block,
    )


def main() -> int:
    manifest = yaml.safe_load(MANIFEST_PATH.read_text())
    groups = collect_groups(manifest)

    for pkgname, group in groups.items():
        pkg_dir = REPO_ROOT / pkgname
        pkgbuild_path = pkg_dir / "PKGBUILD"

        # Refuse to clobber a hand-authored package that happens to collide in name.
        if pkgbuild_path.exists() and not pkgbuild_path.read_text().startswith(MARKER):
            print(f"refusing to overwrite hand-authored {pkgbuild_path}", file=sys.stderr)
            return 1

        pkg_dir.mkdir(exist_ok=True)
        pkgbuild_path.write_text(render_pkgbuild(pkgname, group["description"], group["packages"]))

    print(f"Generated {len(groups)} meta-package(s) at pkgver={PKGVER}.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
