#!/usr/bin/env python3
"""Regenerate meta-package PKGBUILDs from manifest.yaml.

Run only via .github/workflows/generator.yml -- not intended for local use.
Each `modules.<name>` (and each `modules.live_install.subgroups.<name>`)
becomes a `bitglyph-<name>-meta` directory with a generated PKGBUILD whose
`depends=()` mirrors the manifest's package list.
"""
import re
import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
MANIFEST_PATH = REPO_ROOT / "manifest.yaml"
MARKER = "# GENERATED FILE"

PKGBUILD_TEMPLATE = """{marker} -- do not edit directly.
# Regenerated by ci/generate_meta_packages.py from manifest.yaml.
pkgname={pkgname}
pkgver={pkgver}
pkgrel=1
pkgdesc="{pkgdesc}"
arch=('any')
url="https://github.com/BitGlyph/bitglyph-PKGBUILDs"
license=('MIT')
depends=(
{depends}
)

package() {{
  : # nothing to install, this exists purely to pull in dependencies
}}
"""


def slugify(name: str) -> str:
    return name.replace("_", "-")


def clean_description(desc: str) -> str:
    return " ".join(desc.split()).replace('"', "'")


def collect_groups(manifest: dict) -> dict[str, dict]:
    """Flatten modules (and live_install subgroups) into pkgname -> {description, packages}."""
    groups = {}
    for mod_name, mod in manifest["modules"].items():
        if "subgroups" in mod:
            for sub_name, sub in mod["subgroups"].items():
                pkgname = f"bitglyph-{slugify(mod_name)}-{slugify(sub_name)}-meta"
                groups[pkgname] = {
                    "description": sub.get("description", ""),
                    "packages": sub.get("packages", []),
                }
        else:
            pkgname = f"bitglyph-{slugify(mod_name)}-meta"
            groups[pkgname] = {
                "description": mod.get("description", ""),
                "packages": mod.get("packages", []),
            }
    return groups


def existing_pkgver_and_depends(pkgbuild_path: Path) -> tuple[int, list[str]]:
    text = pkgbuild_path.read_text()
    ver_match = re.search(r"^pkgver=(\d+)", text, re.MULTILINE)
    deps_match = re.search(r"depends=\((.*?)\)", text, re.DOTALL)
    pkgver = int(ver_match.group(1)) if ver_match else 0
    deps = []
    if deps_match:
        deps = [line.strip() for line in deps_match.group(1).splitlines() if line.strip()]
    return pkgver, deps


def render_pkgbuild(pkgname: str, pkgver: int, description: str, packages: list[str]) -> str:
    depends_block = "\n".join(f"  {pkg}" for pkg in packages)
    return PKGBUILD_TEMPLATE.format(
        marker=MARKER,
        pkgname=pkgname,
        pkgver=pkgver,
        pkgdesc=clean_description(description),
        depends=depends_block,
    )


def is_generated(pkgbuild_path: Path) -> bool:
    if not pkgbuild_path.exists():
        return False
    return pkgbuild_path.read_text().startswith(MARKER)


def main() -> int:
    manifest = yaml.safe_load(MANIFEST_PATH.read_text())
    groups = collect_groups(manifest)

    changed = []

    for pkgname, group in groups.items():
        pkg_dir = REPO_ROOT / pkgname
        pkgbuild_path = pkg_dir / "PKGBUILD"
        packages = group["packages"]

        if pkgbuild_path.exists():
            old_pkgver, old_deps = existing_pkgver_and_depends(pkgbuild_path)
            pkgver = old_pkgver + 1 if old_deps != packages else old_pkgver
            if pkgver == 0:
                pkgver = 1
        else:
            pkgver = 1

        new_content = render_pkgbuild(pkgname, pkgver, group["description"], packages)
        if not pkgbuild_path.exists() or pkgbuild_path.read_text() != new_content:
            pkg_dir.mkdir(exist_ok=True)
            pkgbuild_path.write_text(new_content)
            changed.append(pkgname)

    # Remove generated dirs for groups no longer present in the manifest.
    for entry in REPO_ROOT.iterdir():
        if not entry.is_dir() or entry.name.startswith("."):
            continue
        pkgbuild_path = entry / "PKGBUILD"
        if entry.name not in groups and is_generated(pkgbuild_path):
            for f in entry.iterdir():
                f.unlink()
            entry.rmdir()
            changed.append(f"removed {entry.name}")

    if changed:
        print("Updated:", ", ".join(changed))
    else:
        print("No changes.")

    return 0


if __name__ == "__main__":
    sys.exit(main())
